# Generated by Django 3.2.6 on 2021-08-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='visible_to_public',
            field=models.BooleanField(default=True),
        ),
    ]
